#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : x11vnc
Version  : 00f2b16442b23a06bae6135d953a9b0e76ee4d62
Release  : 3
URL      : https://github.com/LibVNC/x11vnc/archive/00f2b16442b23a06bae6135d953a9b0e76ee4d62.tar.gz
Source0  : https://github.com/LibVNC/x11vnc/archive/00f2b16442b23a06bae6135d953a9b0e76ee4d62.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: x11vnc-bin
Requires: x11vnc-data
Requires: x11vnc-doc
BuildRequires : cairo-dev
BuildRequires : libXinerama-dev
BuildRequires : libXtst-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libvncclient)
BuildRequires : pkgconfig(libvncserver)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xdamage)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
BuildRequires : sed
Patch1: norc4.patch

%description
[![Build Status](https://travis-ci.org/LibVNC/x11vnc.svg?branch=master)](https://travis-ci.org/LibVNC/x11vnc)

%package bin
Summary: bin components for the x11vnc package.
Group: Binaries
Requires: x11vnc-data

%description bin
bin components for the x11vnc package.


%package data
Summary: data components for the x11vnc package.
Group: Data

%description data
data components for the x11vnc package.


%package doc
Summary: doc components for the x11vnc package.
Group: Documentation

%description doc
doc components for the x11vnc package.


%prep
%setup -q -n x11vnc-00f2b16442b23a06bae6135d953a9b0e76ee4d62
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483218453
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/Xdummy
/usr/bin/x11vnc

%files data
%defattr(-,root,root,-)
/usr/share/applications/x11vnc.desktop

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
